#### Link to video: https://drive.google.com/file/d/1Ni3zy1n3UcZ-LoW_KALTiqZhVlbefxZi/view?usp=sharing

## PART 1:
### Create a class Employee and then do the following
• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [5]:
# a. Class Employee
class Employee():
    # b. To count the number of Employees
    count_employee = 0
    def __init__(self, name, family, salary, department): # c. name, family, salary, department
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count_employee += 1

    @staticmethod # the method belong to the class but independent of any instance
    # d. function to average salary
    def average_salary(employee_lst):
        totalSalary = sum(employee.salary for employee in employee_lst)
        averageSalary = totalSalary / len(employee_lst)
        return averageSalary

# e. class FulltimeEmployee inheriting from Class Employee
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)  

# f. Create the instances of Fulltime Employee class and Employee class and call their member functions.
employee1 = Employee("Chandrika", "patibandla", 50000, "IT")
employee2 = Employee("Avinash", "Mandava", 80000, "Doctor")

fulltime_employee1= FulltimeEmployee("Sindhura", "Deshpande", 45000, "IT")
fulltime_employee2 = FulltimeEmployee("Venkatesh", "Iyer", 66000, "Testing")

# List of all employees
employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]

# Print employee count
print("Total number of employees:", Employee.count_employee)

# Print average salary
avg_salary = Employee.average_salary(employees)
print("The Average Salary:",avg_salary)


Total number of employees: 4
The Average Salary: 60250.0


## PART 2

### Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)
(NOT implement it via for loop)

In [9]:
import numpy as np

# a. Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# reshape into 4 by 5
matrix = random_vector.reshape(4,5)

# print original
print("Matrix:\n",matrix)

# get indices of max value in each row
max_indx = np.argmax(matrix, axis=1)
print("\nMax Indices are:\n",max_indx)

# copy the matrix and named as matrix with zeros
matrix_with_zeros = matrix.copy()
# replace max values with 0 using indexs
matrix_with_zeros[np.arange(matrix.shape[0]),max_indx] = 0

print("\nMatrix after replacing max value in each row with 0:\n", matrix_with_zeros)


Matrix:
 [[12.19771163 12.22344314  9.87382482 17.39683708  1.55367721]
 [12.3375415   4.37003409 10.93354947  6.76491874 11.60951792]
 [ 6.28383449  9.71176284 18.16971191 14.99727711  1.99563201]
 [11.44668342  9.91039695 18.31202018 19.98791535 13.93133135]]

Max Indices are:
 [3 0 2 3]

Matrix after replacing max value in each row with 0:
 [[12.19771163 12.22344314  9.87382482  0.          1.55367721]
 [ 0.          4.37003409 10.93354947  6.76491874 11.60951792]
 [ 6.28383449  9.71176284  0.         14.99727711  1.99563201]
 [11.44668342  9.91039695 18.31202018  0.         13.93133135]]
